// D2R QuickSwitch – D2RMM mod (PowerShell version – no AutoHotkey required)
// Generates QuickSwitch.ps1 and QuickSwitch.bat in the game directory.
// Run QuickSwitch.bat before a D2R session – the script waits for the game to launch
// and automatically exits when D2R is closed.

const keyMap = {
  key1: config.key1,
  key2: config.key2,
  key3: config.key3,
  key4: config.key4,
  key5: config.key5,
  key6: config.key6,
  key7: config.key7,
  key8: config.key8,
};

const tooltipDuration = Math.max(0, parseInt(config.tooltipDuration, 10) || 0);
const chatDelay = Math.max(0, parseInt(config.chatDelay, 10) || 100);

// -----------------------------------------------------------------------
// Validation
// -----------------------------------------------------------------------
const usedKeys = {};
for (let i = 1; i <= 8; i++) {
  const k = keyMap["key" + i];
  if (k === "None") continue;
  if (usedKeys[k]) {
    D2RMM.error(
      "Key " +
        k +
        " is assigned to multiple commands (/players " +
        usedKeys[k] +
        " and /players " +
        i +
        "). Please change the configuration in D2RMM.",
    );
  }
  usedKeys[k] = i;
}

// -----------------------------------------------------------------------
// Key name -> VirtualKey code (decimal) mapping
// -----------------------------------------------------------------------
const vkMap = {
  F1: 112,
  F2: 113,
  F3: 114,
  F4: 115,
  F5: 116,
  F6: 117,
  F7: 118,
  F8: 119,
  F9: 120,
  F10: 121,
  F11: 122,
  F12: 123,
};

// Active key bindings array [VK, command]
const bindingLines = [];
for (let i = 1; i <= 8; i++) {
  const k = keyMap["key" + i];
  if (k !== "None" && vkMap[k] !== undefined) {
    bindingLines.push(
      "  [pscustomobject]@{ VK = " +
        vkMap[k] +
        "; Cmd = '/players " +
        i +
        "' }",
    );
  }
}

// -----------------------------------------------------------------------
// Build PowerShell script
// -----------------------------------------------------------------------
const ps = [];

ps.push("# D2R QuickSwitch - generated by D2RMM");
ps.push("# No AutoHotkey required - runs on built-in Windows PowerShell 5+");
ps.push("# Launch via QuickSwitch.bat");
ps.push("");
ps.push("$chatDelay       = " + chatDelay);
ps.push("$tooltipDuration = " + tooltipDuration);
ps.push("");
ps.push("$bindings = @(");
ps.push(bindingLines.join(",\r\n"));
ps.push(")");
ps.push("");

// C# – HotkeyForm with WndProc intercepting WM_HOTKEY
ps.push("Add-Type -AssemblyName System.Windows.Forms");
ps.push("Add-Type -TypeDefinition @'");
ps.push("using System;");
ps.push("using System.Windows.Forms;");
ps.push("using System.Collections.Generic;");
ps.push("using System.Runtime.InteropServices;");
ps.push("using System.Diagnostics;");
ps.push("");
ps.push("public class HotkeyForm : Form {");
ps.push("    private const int WM_HOTKEY = 0x0312;");
ps.push(
  "    public Dictionary<int,string> CmdMap = new Dictionary<int,string>();",
);
ps.push("    public int ChatDelay = 100;");
ps.push("");
ps.push(
  '    [DllImport("user32.dll")] public static extern bool RegisterHotKey(IntPtr h, int id, uint mod, uint vk);',
);
ps.push(
  '    [DllImport("user32.dll")] public static extern bool UnregisterHotKey(IntPtr h, int id);',
);
ps.push(
  '    [DllImport("user32.dll")] private static extern IntPtr GetForegroundWindow();',
);
ps.push(
  '    [DllImport("user32.dll")] private static extern uint GetWindowThreadProcessId(IntPtr hWnd, out uint pid);',
);
ps.push("");
ps.push("    protected override void WndProc(ref Message m) {");
ps.push(
  "        if (m.Msg == WM_HOTKEY && CmdMap.ContainsKey((int)m.WParam)) {",
);
ps.push("            IntPtr hwnd = GetForegroundWindow();");
ps.push("            uint pid = 0;");
ps.push("            GetWindowThreadProcessId(hwnd, out pid);");
ps.push("            try {");
ps.push("                Process proc = Process.GetProcessById((int)pid);");
ps.push('                if (proc.ProcessName == "D2R") {');
ps.push("                    string cmd = CmdMap[(int)m.WParam];");
ps.push('                    SendKeys.SendWait("{ENTER}");');
ps.push("                    System.Threading.Thread.Sleep(ChatDelay);");
ps.push("                    // SendKeys requires escaping special characters");
ps.push('                    SendKeys.SendWait(cmd.Replace("/","{/}"));');
ps.push("                    System.Threading.Thread.Sleep(50);");
ps.push('                    SendKeys.SendWait("{ENTER}");');
ps.push("                }");
ps.push("            } catch {}");
ps.push("        }");
ps.push("        base.WndProc(ref m);");
ps.push("    }");
ps.push("}");
ps.push("'@ -ReferencedAssemblies System.Windows.Forms");
ps.push("");

// Form + hotkey registration
ps.push("$form = New-Object HotkeyForm");
ps.push("$form.WindowState   = 'Minimized'");
ps.push("$form.ShowInTaskbar = $false");
ps.push("$form.Opacity       = 0");
ps.push("$form.ChatDelay     = $chatDelay");
ps.push("$form.Show()");
ps.push("$form.Hide()");
ps.push("");
ps.push("$id = 1");
ps.push("foreach ($b in $bindings) {");
ps.push(
  "    [HotkeyForm]::RegisterHotKey($form.Handle, $id, 0, $b.VK) | Out-Null",
);
ps.push("    $form.CmdMap[$id] = $b.Cmd");
ps.push("    $id++");
ps.push("}");
ps.push("$totalHotkeys = $id - 1");
ps.push("");

// Timer monitoring D2R process
ps.push("$script:wasRunning = $false");
ps.push("$timer = New-Object System.Windows.Forms.Timer");
ps.push("$timer.Interval = 2000");
ps.push("$timer.Add_Tick({");
ps.push(
  "    $running = [bool](Get-Process -Name 'D2R' -ErrorAction SilentlyContinue)",
);
ps.push("    if ($running -and -not $script:wasRunning) {");
ps.push("        $script:wasRunning = $true");
ps.push(
  "        Write-Host '[QuickSwitch] D2R detected - hotkeys active.' -ForegroundColor Green",
);
ps.push("    } elseif (-not $running -and $script:wasRunning) {");
ps.push(
  "        Write-Host '[QuickSwitch] D2R closed - exiting.' -ForegroundColor Red",
);
ps.push("        for ($i = 1; $i -le $script:totalHotkeys; $i++) {");
ps.push(
  "            [HotkeyForm]::UnregisterHotKey($form.Handle, $i) | Out-Null",
);
ps.push("        }");
ps.push("        [System.Windows.Forms.Application]::Exit()");
ps.push("    }");
ps.push("})");
ps.push("$timer.Start()");
ps.push("");
ps.push(
  "Write-Host '[QuickSwitch] Running - waiting for D2R...' -ForegroundColor Yellow",
);
ps.push("[System.Windows.Forms.Application]::Run($form)");

const psContent = ps.join("\r\n");
D2RMM.writeTxt("QuickSwitch.ps1", psContent);

// -----------------------------------------------------------------------
// Generate BAT file – launches PS1 in background (no window, non-blocking)
// -----------------------------------------------------------------------
const bat = [];
bat.push("@echo off");
bat.push("title D2R QuickSwitch");
bat.push("");
bat.push(":: Check if the script is already running");
bat.push(
  "powershell -NoProfile -Command \"exit ([bool](Get-WmiObject Win32_Process -Filter \"Name='powershell.exe'\" | Where-Object { $_.CommandLine -like '*QuickSwitch.ps1*' }))\"",
);
bat.push("if %ERRORLEVEL%==1 (");
bat.push("  echo [D2R QuickSwitch] Script is already running.");
bat.push("  timeout /t 2 >nul");
bat.push("  exit /b 0");
bat.push(")");
bat.push("");
bat.push('set "SCRIPT=%~dp0QuickSwitch.ps1"');
bat.push('if not exist "%SCRIPT%" (');
bat.push("  echo ERROR: QuickSwitch.ps1 not found next to this .bat");
bat.push("  echo Please reinstall the mod via D2RMM.");
bat.push("  pause");
bat.push("  exit /b 1");
bat.push(")");
bat.push("");
bat.push(":: Launch PS1 in a separate hidden window");
bat.push(
  'start "" /B powershell -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File "%SCRIPT%"',
);
bat.push("echo [D2R QuickSwitch] Started! Waiting for D2R...");
bat.push("timeout /t 2 >nul");
bat.push("exit /b 0");

D2RMM.writeTxt("QuickSwitch.bat", bat.join("\r\n"));
